apps/app_empty.rs
src/ioreg/ioreg.rs
src/macro/platformtree.rs
src/platformtree/builder/meta_args.rs
src/platformtree/builder/mod.rs
src/platformtree/platformtree.rs
src/zinc/drivers/dht22.rs
src/zinc/drivers/lcd/c12332.rs
src/zinc/drivers/lcd/ili9341.rs
src/zinc/hal/isr.rs
src/zinc/hal/tiva_c/sysctl.rs
src/zinc/util/shared.rs
src/zinc/util/strconv.rs
thirdparty/librlibc/src/lib.rs

This should fix almost all warnings with ```rustc 1.0.0-nightly (522d09dfe 2015-02-19) (built 2015-02-21)```
Basically some int/uint -> usize/isize replacement and some feature attributes

Fix warnings

---

.travis.yml
Cargo.toml
ci/build-examples.sh
examples/app_blink_stm32l1.rs
examples/app_blink_tiva_c.rs
examples/app_bluenrg_stm32l1.rs
examples/app_dht22.rs
examples/app_empty.rs
examples/app_lcd_tiva_c.rs
examples/app_uart_tiva_c.rs
examples/app_usart_stm32l1.rs
src/hal/k20/layout.ld
src/hal/layout_common.ld
src/util/support.rs

* Fixes #289
* Fixes some issues with some examples that were introduced when #285 landed.

Fix #289: add examples to travis (and fix example fallout from #285)

---

.travis.yml
Cargo.toml
examples/app_blink.rs
examples/app_blink_k20.rs
examples/app_blink_stm32f4.rs
examples/app_blink_stm32l1.rs
examples/app_nothing.rs
examples/app_usart_stm32l1.rs
macro_zinc/Cargo.toml
macro_zinc/src/lib.rs

This removes the `#[start]` boilerplate code by adding a simple `#[zinc_main]` annotation that allows the user to specify which of their methods should be called at startup.
This is needed because there should be a straightforward way to consume `zinc` without `platformtree`. Right now, platformtree will provide `#[start]` code, but non-platformtree consumers are currently required to provide a boilerplate implementation.
Only drawback I really is is having to maintain another syntax extension... but zinc is already so heavily dependent upon them that I don't see that as much of a downside at all, especially considering the simplicity of this one.

Provide straightforward way to consume zinc without platformtree (remove #[start] boilerplate)

---

Makefile.in

The user can now invoke builds like the following:
$ make DEBUG=true EXAMPLE_NAME=blink
This will build artifacts with the dev profile that includes
debug symbols and eliminates optimization that would normally be
included.  This is necessary to get a reasonable debugging experience
in many cases.
A few options were also modified in order to allow for the user
to override them if desired.

build: allow user to build with dev/debug profile

---

.travis.yml
Cargo.toml
Makefile.in
build.rs
src/hal/cortex_m3/mod.rs
src/hal/isr.rs
src/os/mod.rs
src/util/app.rs
src/util/mod.rs

As exposed in #306, there's still a need for cargo features that aren't MCU features, and `build.rs` needs a way to tell them apart.
* Prefixed all the MCU features with `mcu_`
* Converted the old `cfg_multitasking` config flag to a cargo feature (`multitasking`)

Cargo feature refactoring

---

ioreg/Cargo.toml
ioreg/src/builder/accessors.rs
ioreg/src/builder/getter.rs
ioreg/src/builder/register.rs
ioreg/src/builder/setter.rs
ioreg/src/builder/union.rs
ioreg/src/builder/utils.rs
ioreg/src/lib.rs
ioreg/src/node.rs
ioreg/src/parser.rs

Makes more meaningful feedback from macro builders.
Fixes  (for ioreg, not for platformtree) #99

Minimize use of DUMMY_SP

---

ioreg/src/builder/union.rs

Closes #274 
This method now returns usize do to upstream changes in what rust expects from a fixed length vec type definition.

ioreg: rename expr_u64 -> expr_usize

---

Cargo.toml
src/hal/cortex_common/irq.rs
src/hal/cortex_m3/isr.rs
src/hal/cortex_m3/lock.rs
src/hal/cortex_m3/sched.rs
src/hal/isr.rs
src/hal/mod.rs
src/lib.rs
src/util/shared.rs
src/util/support.rs

This will make zinc compatible for compilation for the build system.
Eventually, we should move architecture specific code somewhere, but this will suffice until then.

build: feature gate arch and cpu specific code

---

ioreg/src/builder/accessors.rs
ioreg/src/builder/setter.rs
ioreg/src/builder/union.rs
ioreg/src/lib.rs
ioreg/src/node.rs
ioreg/src/parser.rs
ioreg/tests/test.rs

Added support for `ignoring_state` and placement getter, that allows code like this:
```rust
regs::SYSCON().sysoscctrl.ignoring_state()
.set_bypass(regs::SYSCON_sysoscctrl_bypass::NOBYPASS)
.set_freqrange(regs::SYSCON_sysoscctrl_freqrange::LOW);
```

Ioreg improvements

---

examples/app_blink.rs
examples/app_blink_k20.rs
examples/app_blink_k20_isr.rs
examples/app_blink_pt.rs
examples/app_blink_stm32f4.rs
examples/app_blink_stm32l1.rs
examples/app_blink_tiva_c.rs
examples/app_bluenrg_stm32l1.rs
examples/app_dht22.rs
examples/app_empty.rs
examples/app_lcd_tiva_c.rs
examples/app_nothing.rs
examples/app_uart.rs
examples/app_uart_tiva_c.rs
examples/app_usart_stm32l1.rs
ioreg/src/builder/accessors.rs
ioreg/src/builder/setter.rs
ioreg/src/lib.rs
ioreg/src/node.rs
ioreg/src/parser.rs
platformtree/src/builder/mod.rs
platformtree/src/lib.rs
src/lib.rs
volatile_cell/lib.rs

* Some things got feature-gated
* `from_str` deprecated in favor of `From<T>`.
* rust-lang/rust#15311 caused possible rethinking of `max_by` and `min_by` on iterators.
* `Vec::push_all` feature-gated, but I replaced it so that we don't depend on **another** unstable feature.
It looks like it's a long road ahead before zinc will be able to track the stable channel or Rust.

6/23 Nightly fallout

---

src/hal/stm32f4/pin.rs

This adds the `toggle` function to the stm32f4's GPIO pins. This is a ported function from the HAL provided by STM:
```c
void HAL_GPIO_TogglePin(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin)
{
/* Check the parameters */
assert_param(IS_GPIO_PIN(GPIO_Pin));
GPIOx->ODR ^= GPIO_Pin;
}
```

Added toggle for the stm32f4 GPIO

---

ioreg/src/builder/accessors.rs
ioreg/src/builder/getter.rs
ioreg/src/builder/register.rs
ioreg/src/builder/setter.rs
ioreg/src/builder/union.rs
ioreg/src/builder/utils.rs
ioreg/src/parser.rs
macro_platformtree/src/lib.rs
platformtree/src/parser.rs

It may need testing, but this appears to fix the issue on my lpc17xx.
It also fixes two type errors in platformtree by using deref().

Fix for removal of get_ident()

---

examples/blink_k20/src/main.rs
examples/blink_k20_isr/src/main.rs
examples/blink_lpc17xx/src/main.rs
examples/blink_pt/src/main.rs
examples/blink_stm32f4/src/main.rs
examples/blink_stm32l1/src/main.rs
examples/blink_tiva_c/src/main.rs
examples/bluenrg_stm32l1/src/main.rs
examples/dht22/src/main.rs
examples/empty/src/main.rs
examples/lcd_tiva_c/src/main.rs
examples/uart/src/main.rs
examples/uart_tiva_c/src/main.rs
examples/usart_stm32l1/src/main.rs
ioreg/tests/test.rs
platformtree/src/builder/meta_args.rs
platformtree/src/lib.rs
src/lib.rs
src/os/cond_var.rs
src/os/mutex.rs
src/util/app.rs
volatile_cell/lib.rs

As described at https://github.com/rust-lang/rfcs/pull/1184, rustc nightly now automatically imports core when using no_std

Fixes for rust nightly changes

---

ioreg/src/parser.rs
src/lib.rs

Trying to build blink_stmf3f4 I came across a couple of minor tweaks to get the code to compile with the current nightly "rustc 1.5.0-nightly (81b3b27cf 2015-10-11)"

A couple of minor changes to make code compatible with current rust nightly

---

build.rs
src/hal/lpc11xx/iomem.ld

This allows removing empty iomem.ld files from the repository.
Eventually all examples will be migrated to ioregs! macros and the code
snippet from build.rs can be removed.

Attempt to copy iomem.ld to $OUT_DIR only if it exists

---

.cargo/config
Cargo.toml
support/build-jenkins.sh
thumbv6m-none-eabi.json
volatile_cell/Cargo.toml

See individual commit messages for details. This PR will probably fail to build until https://github.com/hackndev/rlibc/pull/2 is merged.

thumbv6m-none-eabi target rename and cleanup

---

src/hal/cortex_m0/isr.rs
src/hal/isr.rs
src/hal/lpc11xx/layout.ld

Instead of reusing module from Cortex-M3, create specific module for M0,
containing only exceptions documented on the ARMv6-M Architecture
Reference Manual.
This allows removing the unnecessary "isr_reserved_1" symbol from the
linker scripts for Cortex-M0 based boards and setting reserved ISR vector entries.

Create proper isr_cortex_m0 module

---

examples/adc_lpc17xx/Cargo.toml
examples/adc_lpc17xx/src/main.rs
src/hal/lpc17xx/iomem.ld
src/hal/lpc17xx/pin.rs
src/hal/pin.rs
support/build-jenkins.sh

Added support for the adc channels of the lpc17xx. The setup and read sequence is borrowed from mbed. Tested on a LPCxpresso 1796 board. This patch also adds some lines to configure the pin modes - not yet integrated in the pt - but needed for adc pins.

Added ADC support for lpc17xx

---

volatile_cell/lib.rs

Fixes an issue pointed out at https://github.com/hackndev/zinc/issues/367.

VolatileCell requires T: Copy now

---

src/util/lang_items.rs

When zinc is used and a test is added to the application, some functions are double defined because building with tests always includes std. This patch avoids that by omitting these functions when feature test is set. I forward test from the application to zinc:
[features]                                                                                                                                                                                                                                                                                                                                                                                                                                   test = ["zinc/test"]

Avoid double definition when used in test

---

ioreg/Cargo.toml
ioreg/src/builder/accessors.rs
ioreg/src/builder/getter.rs
ioreg/src/builder/register.rs
ioreg/src/builder/setter.rs
ioreg/src/builder/union.rs
ioreg/src/builder/utils.rs
ioreg/src/lib.rs
ioreg/src/parser.rs
macro_platformtree/src/lib.rs
platformtree/src/builder/meta_args.rs
platformtree/src/builder/mod.rs
platformtree/src/builder/os.rs
platformtree/src/lib.rs
platformtree/src/parser.rs
platformtree/src/test_helpers.rs
src/drivers/dht22_pt.rs
src/hal/lpc17xx/pin_pt.rs
src/hal/lpc17xx/system_clock_pt.rs
src/hal/lpc17xx/timer_pt.rs
src/hal/lpc17xx/uart_pt.rs
src/util/lang_items.rs
thumbv7em-none-eabi.json
thumbv7m-none-eabi.json

This fixes platformtree!, ioreg! and lang items.

Update for rust 1.10.0-nightly

---

.travis.yml

This fixes the travis file so the build is done.
Solves #382 
Note that zinc does not compile correctly.

Fixed missing key in travis build

---

examples/blink_stm32f4/src/main.rs

This example runs using the HSI clock which is 16 MHz. This means
that we need to pass 16 in rather than 25.
I confirmed (with my Logic analyzer) that with this patch that the
timings are correct on the STM32FDISC board which uses an STM32F407.

blink_stm32f4: Fix timer

---

ioreg/src/lib.rs
ioreg/src/parser.rs
macro_platformtree/src/lib.rs
platformtree/src/builder/mod.rs
platformtree/src/parser.rs

In the latest rust nightly TokenTree was moved out of syntax::ast into syntax::tokenstream
This changes the ioreg code accordingly.

Reflect the move of TokenTree

---

platformtree/Cargo.toml
platformtree/src/builder/mcu.rs
platformtree/src/lib.rs
src/hal/tiva_c/pin.rs
src/hal/tiva_c/pin_pt.rs
src/hal/tiva_c/platformtree.rs
src/hal/tiva_c/sysctl.rs
src/hal/tiva_c/timer.rs
src/hal/tiva_c/timer_pt.rs
src/hal/tiva_c/uart.rs
src/hal/tiva_c/uart_pt.rs
src/lib.rs

This pull request fixes regressions in the `mcu_tiva_c` platform tree allowing Zinc to be built for the Stellaris Launchpad and Tiva C boards. I've test-compiled [a boilerplate project](https://github.com/jamwaffles/zinc-tiva-c-example) onto my Stellaris Launchpad which works, and I've compiled a few of the `tiva_c_*` projects under `examples/`, which built fine as well, although I haven't flashed them to any boards yet.
Apologies for the messy commits. I hope the overall diff makes apparent what I did. There's a lot of `.unwrap()` unsafe code in the platform tree files, but that seems to be on par with the lpc17xx files, so I left my changes as is. An incorrect platform tree will panic with no error currently, but that seems to be a general issue with Zinc at the moment as the codebase …

Fix platform tree for Tiva C/Stellaris Launchpad boards

---

src/hal/tiva_c/mod.rs
src/hal/tiva_c/spi.rs
src/hal/tiva_c/sysctl.rs

This PR adds reasonably basic SPI support for the Tiva C HAL. It allows choosing one of 4 SSI peripherals to use for SPI transmission as well as the desired frequency to operate at. Other options should be pretty easy to add in the future.
I've made a pretty good stab at documenting this module; `cargo doc --features=mcu_tiva_c` produces some docs, even with a complete example. I'd love to see an awesome set of documentation for Zinc, so this is my contribution to the start of it :).

Tiva C SPI support

---

volatile_cell/Cargo.toml

volatile_cell: Add version for expectest dependency

---

src/hal/tiva_c/pin.rs
src/hal/tiva_c/sysctl.rs
src/hal/tiva_c/timer.rs
src/hal/tiva_c/uart.rs

tiva_c docs should ignore only actual pin instantiations
